### ISSUE TITLE
0.7.0 broken: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by simllll** [visualfanatic/svg-to-vue#19]
it seems there is no render function anymore, and therefore vue cannot mount the svg.

0.7.0 (broken):
![image](https://user-images.githubusercontent.com/5757263/74243662-7060d180-4ce0-11ea-9a7d-66f8395984ac.png)

0.6.0 (works):
![image](https://user-images.githubusercontent.com/5757263/74244193-5673be80-4ce1-11ea-96b0-eaddf3ad0473.png)

```
[Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <Anonymous>
       <Anonymous>

```

Any idea what I can try to get it up and running again with the new version?

Thanks

**Comment by robsonsobral** [comment]
I guess it's related to the commit https://github.com/visualfanatic/svg-to-vue/commit/4970d54c8a95ad0c7b9bc78c78d0f20e96618215

**Comment by simllll** [comment]
@visualfanatic do you have any input on this? Still stuck with the old version.

**Comment by damianstasik** [comment]
Please try the latest beta version `vue-svg-loader@beta` and replace `babel-loader` with `vue-loader`.
