### ISSUE TITLE
0.4.0 version can't be transpiled by Babel

### ISSUE THREAD

**Issue by menthol** [visualfanatic/svg-to-vue#6]
In 0.4.0 version, you use a long big string with the rest operator.

The rest operator isn't transpiled by Babel so old browser to not work with this version.

**Comment by thomasaull** [comment]
Having the same problem

**Comment by DamianMullins** [comment]
Same for me as well.

**Comment by conoverm** [comment]
How would you solve this? Would you add a step before this line:
https://github.com/visualfanatic/svg-to-vue/blob/master/index.js#L34

And then send the "renderFunction" through Babel?

**Comment by DamianMullins** [comment]
I think v0.4.0 is deployed from the `next` branch. You can [see the rest operators in this file](https://github.com/visualfanatic/svg-to-vue/blob/next/index.js). 

So I guess these lines would have to be replaced or transpiled?

**Comment by damianstasik** [comment]
I just released `svg-to-vue@0.5.0` and `vue-svg-loader@0.13.0`, remember to add `babel-loader` before the `vue-svg-loader` in your webpack config, check the config to see how.
